version: '3.5'

services:
  redis:
    container_name: music_redis
    image: redis:6.2.5
    command: 'redis-server --appendonly yes --requirepass ${REDIS_PASS}'
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - music-net
    restart: unless-stopped
    volumes:
      - redis:/data/music/redis

networks:
  music-net:
    driver: bridge

volumes:
  redis:
